language: r
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite(c('limma', 'sva'))"
  - Rscript -e 'install.packages("Rmosek")'